server:
  port: 53
  address: 127.0.0.1

domains:
  - name: pure-dns.local
    host: localhost

log:
  format: "string" 
  access_log: "stdout" 
  access_level: "debug"
  error_log: "stderr"
  error_level: "error"
    